apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pod-mutation-deployment
  namespace: webhooks
  labels:
    name: pod-mutation-webhook
spec:
  replicas: 1
  template:
    metadata:
      name: pod-mutation-webhook 
      labels:
        type: webhook 
        name: pod-mutation-webhook
    spec:
      containers:
        - name: webhook
          image: pod-mutation-webhook:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: 50Mi
              cpu: 300m
            requests:
              memory: 50Mi
              cpu: 300m
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: pod-mutation-webhook-certs