apiVersion: v1
kind: Service
metadata:
  name: pod-mutation-service
  namespace: webhooks
  labels:
    name: pod-mutation-webhook
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8080
  selector:
    type: webhook 
    name: pod-mutation-webhook