apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: webhooks
webhooks:
  - name: webhook-server.mutation.svc
    clientConfig:
      service:
        name: webhook-server
        namespace: webhooks
        path: "/"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]